---
title: "Untitled"
author: "Mattia Mohr, 12100058"
date: "29 10 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
#library(Rcpp)
library(sf)

```


#Laden der Datensätze
```{r}
btw_data <- readRDS("~/RStudio/Anfängerprakt. BTW21/AP-BTW2021/btw_data.RDS")
btw_trimmed_data <- readRDS("~/RStudio/Anfängerprakt. BTW21/AP-BTW2021/btw_trimmed_data.RDS")
```


#Wahlkreiskarte
```{r}
wk_path <- "Raw Data/btw21_geometrie_wahlkreise_geo_shp_WGS84/Geometrie_Wahlkreise_20DBT_geo.shp"
wk_shp <- st_read(wk_path)
glimpse(wk_shp)

wk_shp$LAND_NR <- NULL
wk_shp$LAND_NAME <- NULL



btw_geo_data <- left_join(btw_data, wk_shp, by= c("Wahlkreis.Nr" = "WKR_NR"))
btw_geo_data$WKR_NAME <- NULL

#Wahlkreise mit hohem Anteil an Jugendlichen
wk_shp %>% 
  ggplot() +
  geom_sf(fill = btw_trimmed_data[["f18t24.Perctange"]], show.legend = T)+
  scale_fill_brewer(type = "div")
#Skala ändern

#Gewinnerpartei in jedem Wahlkreis
btw_trimmed_data %>%
  mutate(Direktmandat = max(SPD.Erst.End.Perc, FDP.Erst.End.Perc, AFD.Erst.End.Perc, LINKE.Erst.End.Perc, na.rm = T)) %>%
  select(Direktmandat)

wk_shp %>% 
  ggplot() +
  geom_sf(fill = btw_trimmed_data$Direktmandat)#max(btw_trimmed_data[["CDU.Erst.End.Perc"]], btw_trimmed_data[["FDP.Erst.End.Perc"]]))
#funktioniert noch nicht
#btw_geo_data %>% 
#ggplot()+
#geom_sf(aes(geometry= geometry, fill=btw_kerg_trimmed_wk$Wahlbeteiligung.Zweit.End))
  

```

#Bundesländerkarte
```{r}
bl_path <- "Raw Data/laender.shp" #"C:\Users\matti\Documents\RStudio\Anfängerprakt. BTW21\AP-BTW2021\Raw Data\laender.shp"
#st_drivers(bl_path)


bl_shp <- st_read(bl_path)
glimpse(bl_shp)

#bl_shp$LAND_NR <- NULL
#bl_shp$LAND_NAME <- NULL



btw_geo_data <- left_join(btw_data, bl_shp, by= c("Bundesland.Nr" = "BL_NR"))
btw_geo_data$WKR_NAME <- NULL

bl_shp %>% 
  ggplot() +
  geom_sf()
```


#Alter+Parteien?
```{r}
btw_trimmed_data %>% 
  ggplot()+
  geom_point(aes(x=f18t24.Perctange, y = GRÜNE.Erst.End.Perc, color= Bundesland.Nr), position = "jitter")#Bundesland/color discrete machen?
#interessant mit: AFD, Grüne, (SPD)

btw_trimmed_data %>% 
  ggplot()+
  geom_point(aes(x=f18t24.Perctange, y = GRÜNE.Erst.End.Perc, color= Bundesland.Nr), position = "jitter")+
  labs(x = "Anteil an 18-24-Jährigen in %", "Erststimmenanteil der Grünen in Prozent", title = "Wahlkreise in Betrachtung von Anteil junger Leute/ Erststimmen fü Grüne")

btw_trimmed_data %>% 
  ggplot()+
  geom_point(aes(x=f18t24.Perctange, y = CDU.Erst.End.Perc, color= WohnFlaech.EW), position = "jitter") 

```


#Parteien nach Bundesländer
```{r}
btw_kerg_trimmed_bundeslaender %>%
  select(Wahlkreis.Nr,Gebiet, ends_with(".Erst.End.Perc")) %>%
  ggplot()+
  geom_bar(aes(x = Gebiet), fill = FDP.Erst.End.Perc, stat = "identity")
, y = c(FDP.Erst.End.Perc, CDU.Erst.End.Perc)
```


#Parteien Ost/West
```{r}
btw_kerg_bundeslaender %>%
  
```




#Alter Bundesländer + Wählerschaft
```{r}


struktur_only <- btw_trimmed_data %>% 
  select(1:2,76:ncol(btw_trimmed_data))

btw_trimmed_data %>%
  filter(f18t24.Perctange <5)

btw_struk_laender %>%
  ggplot(aes(Land, f18t24.Perctange))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0))

btw_struk_laender %>%
  ggplot(aes(Bundesland.Nr., f18t24.Perctange, fill = Land))+
  geom_bar(stat = "identity")+
  scale_fill_discrete(name = "Bundesländer", labels = c("BW", "BY", "Berlin", "BB", "Bremen", "HH", "Hessen", "M-V", "NS", "NRW", "RPF", "SL", "Sachs.", "Sachs.-A.", "S-H", "Thür."))

wenig_jugend <- btw_struk_laender %>%
  filter(f18t24.Perctange < 6) %>%
  select(Bundesland.Nr.)

btw_data %>%
  ggplot(aes(Bundesland.Nr, FDP.Zweit.End))+
  geom_bar(stat = "identity")

btw_trimmed_ %>%
  ggplot()+
  geom_bar(aes(Bundesland.Nr., f18t24.Perctange, fill = Land), stat = "identity")+
  geom_bar(aes(Bundesland.Nr, FDP.Zweit.End), stat = "identity")
```




#Verlust CDU/CSU + Gewinn SPD

```{r}
#Wahlkreise
#CDU&SPD junge Leute
btw_trimmed_data %>% 
  ggplot()+
  geom_point(aes(x = CDU.Erst.End.Perc, y= SPD.Erst.End.Perc, color= f18t24.Perctange), position = "jitter")+
  scale_fill_brewer(palette = "Oranges")#YlOrRd

#Bundesländer
#CDU&SPD junge Leute
btw_kerg_trimmed_bundeslaender %>% 
  ggplot()+
  geom_point(aes(x = CDU.Erst.End.Perc, y= SPD.Erst.End.Perc, size= 
                  btw_struk_laender$f18t24.Perctange ),color = "darkblue", position = "jitter")+ #oder mit color
  geom_point(aes(x = CSU.Erst.End.Perc, y= SPD.Erst.End.Perc, size= 
                  btw_struk_laender$f18t24.Perctange), color = "darkblue")+  
  labs(title = "Bundesländer: SPD und CDU/CSU im Merkmal Anteil an 18 bis 24-Jährigen", x = "CDU/CSU in %", y = "SPD in Prozent")
  #scale_fill_brewer(palette = "Oranges")#YlOrRd

#CDU&SPD ältere Leute
btw_kerg_trimmed_bundeslaender %>% 
  ggplot()+
  geom_point(aes(x = CDU.Erst.End.Perc, y= SPD.Erst.End.Perc, size= 
                  btw_struk_laender$f60t74.Perctange ),color = "darkblue", position = "jitter")+ #oder mit color
  geom_point(aes(x = CSU.Erst.End.Perc, y= SPD.Erst.End.Perc, size= 
                  btw_struk_laender$f60t74.Perctange), color = "darkblue")+  
  labs(title = "Bundesländer: SPD und CDU/CSU im Merkmal Anteil an 60 bis 74-Jährigen", x = "CDU/CSU in %", y = "SPD in Prozent")



#CDU&SPD Prozentunterschiede in den verschiedenen Bundesländern

btw_kerg_trimmed_bundeslaender %>%
  ggplot()+
  geom_bar(aes(y = CDU.Erst.End.Perc, x = "CDU/CSU"),stat = "summary", fun = "identity", fill = "black") +
  geom_bar(aes(y = SPD.Erst.End.Perc, x = "SPD"),stat = "summary", fun = "identity", fill = "red")+
  facet_wrap(~Gebiet)+
  geom_bar(aes(y = CSU.Erst.End.Perc, x = "CDU/CSU"),stat = "summary", fill = "black") +
  labs(x = "CDU/CSU und SPD", y = "Anteil in %", title = "Vergleich Stimmenanteil der CDU/CSU und SPD in den Bundesländern")

```



#Erst/Zweitstimmen
```{r}
#Boxplot Unterschied Erst/Zweitstimmen über alle Wahlkreise
btw_trimmed_data %>%
  ggplot()+
  geom_boxplot(aes(x = "Erststimmen", y = CDU.Erst.End.Perc))+
  geom_boxplot(aes(x = "Zweitstimmen", y = CDU.Zweit.End.Perc))

btw_trimmed_data %>%
  ggplot()+
  geom_boxplot(aes(x = "Erststimmen", y = CDU.Erst.End.Perc))+
  geom_boxplot(aes(x = "Zweitstimmen", y = CDU.Zweit.End.Perc))+
   geom_boxplot(aes(x = "Erststimmen", y = CSU.Erst.End.Perc))+
  geom_boxplot(aes(x = "Zweitstimmen", y = CSU.Zweit.End.Perc))
#Linke mehr Zweitstimmen??
#CDU deutlich weniger
```

















#nicht anschauen
```{r}



wenig_jugend_wk <- btw_trimmed_data %>%
  filter(f18t24.Perctange < 5) %>%
  sum($FDP.Erst.End.Perc)

perc_wenig_jugend <- c(sum(wenig_jugend_wk[["CDU.Erst.End.Perc"]]), sum(wenig_jugend_wk[["SPD.Erst.End.Perc"]]),sum(wenig_jugend_wk[["AFD.Erst.End.Perc"]]), sum(wenig_jugend_wk[["FDP.Erst.End.Perc"]]), sum(wenig_jugend_wk[["LINKE.Erst.End.Perc"]]), sum(wenig_jugend_wk[["GRÜNE.Erst.End.Perc"]]), sum(wenig_jugend_wk[["FW.Erst.End.Perc"]], na.rm = TRUE), sum(wenig_jugend_wk[["Sonstige.Erst.End.Perc"]]))/nrow(wenig_jugend_wk)
names(perc_wenig_jugend) <- c("CDU/CSU", "SPD", "AFD", "FDP", "LINKE", "GRÜNE", "FW", "Sonstige")

#ends_with("Perc") um Parteien rauszufiltern


ggplot(as.data.frame( c(names(perc_wenig_jugend), perc_wenig_jugend), col.names = c("Namen", "Prozentanteile")))+
geom_bar(aes("Namen"))+
coord_flip()

#btw_struk_wk %>%
 # filter(f18t24.Perctange < 5)


try_matrix <- matrix(c("CDU", "SPD", btw_kerg_trimmed_bundeslaender[[1,"CDU.Erst.End.Perc"]], btw_kerg_trimmed_bundeslaender[[1,"SPD.Erst.End.Perc"]]), nrow = 2, byrow = F)
ggplot(as.data.frame(try_matrix))+
  geom_bar(aes(x = try_matrix[,1], y = try_matrix[,2]), stat = "identity")#+
#  scale_y_continuous(limits = c(0, 0.3))


btw_kerg_trimmed_bundeslaender %>% 
  geom_bar()+
  facet_grid(rows = 4, cols = 4)
```

